// packages/nuxt3-blog/components/Header.vue
<template>
  <nav class="nav">
    <Wrapper>
      <!-- 左侧logo -->
      <div></div>
      <!-- 右侧菜单，手机端隐藏 -->
      <ul class="flex">
        <li v-for="item in navList" :key="item.name">
          <nuxt-link :to="item.link" class="pdl-2 pdr-2">{{
            item.name
          }}</nuxt-link>
        </li>
      </ul>
    </Wrapper>
  </nav>
</template>

<script setup lang="ts">
import { ref } from "vue";

const navList = ref([
  { name: "首页", link: "/" },
  { name: "分类", link: "/" },
  { name: "归档", link: "/" },
  { name: "友链", link: "/" },
  { name: "关于", link: "/" },
]);
</script>

<style lang="scss" scoped>
@import "@/styles/var.scss";
.nav {
  height: $nav-height;
  line-height: $nav-height;
}
</style>

// apps/react-client/components/Header/index.tsx
import type { FC } from 'react';
import styles from './index.module.scss';
import Link from 'next/link';
import classNames from 'classnames';
import { useRouter } from 'next/router';
import Search from './Search';

const NAV_LIST = [
  { name: '首页', link: '/' },
  { name: '分类', link: '/category' },
  { name: '归档', link: '/archives' },
  { name: '留言板', link: '/message' },
  { name: '关于', link: '/about-me' },
];

const Header: FC = () => {
  const router = useRouter();
  const pathname = router.pathname;

  console.log('pathname', pathname);

  return (
    <header className={styles['app-header']}>
      <div className={styles['app-header__logo']}>logo</div>
      <nav className={styles['app-header__nav']}>
        <ul className={styles['nav-list']}>
          {NAV_LIST.map(item => {
            return (
              <li
                key={item.name}
                className={classNames(styles['nav-item'], pathname === item.link ? styles['is-active'] : null)}>
                <Link href={item.link}>{item.name}</Link>
              </li>
            );
          })}
        </ul>

        <div>
          <Search />
        </div>
      </nav>
    </header>
  );
};

export default Header;
